alias scr='screen -dRR'
alias cls='printf "\033c"'
alias ll='ls -alF --color'
alias m='less'
alias l='ls -aF --color'
alias psgrep='ps -aux | grep --color'
alias em='emacsclient'
alias ed='emacs --daemon'
